version: "3.9"

networks:
  app_net:
    driver: bridge

volumes:
  pgdata:
  web_node_modules:

services:
  db:
    image: postgres:16
    container_name: project_db
    environment:
      POSTGRES_USER: Ethan
      POSTGRES_PASSWORD: Ethang316
      POSTGRES_DB: project_app_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Ethan -d project_app_db"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: project_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ethanortega316@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Ethang316
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_api
    environment:
      DATABASE_URL: postgresql+psycopg://Ethan:Ethang316@db:5432/project_app_db
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
    volumes:
      - ./backend:/app
    restart: unless-stopped

  web:
    build:
      context: ./frontend/scheduling-project
      dockerfile: Dockerfile
    container_name: project_web
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - api
    ports:
      - "5173:5173"
    networks:
      - app_net
    volumes:
      - ./frontend/scheduling-project:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules
    restart: unless-stopped